# source has to be here
source 'https://supermarket.chef.io/'

metadata

# Local Cookbooks
cookbook 'craft_shared', path: '../craft_shared'
cookbook 'ec2-tags-ohai-plugin', path: '../ec2-tags-ohai-plugin'
