name 'data-service'
maintainer 'Paul'
maintainer_email 'bcampagnolo@me.com'
license 'all_rights'
description 'Installs/Configures data-service'
long_description 'Installs/Configures flask data-service'
version '0.0.1'
